//Justin Pulido
//Person.cpp
//March 10, 2017
//The Person class gets the name, date of birth, and 
//the gender of the person. Then it prints it out.

#include "Person.h"
#include <string>
#include <iostream>

using namespace std;

Person::Person()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -117--74--108--65-1437df22:15bef0504a0:-8000:000000000000086F begin
{
	name = "";
	dob = "";
	gender = "";
}
// section -117--74--108--65-1437df22:15bef0504a0:-8000:000000000000086F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Person::Person(string n, string d, string g)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -117--74--108--65-1437df22:15bef0504a0:-8000:000000000000087E begin
{
	name = n;
	dob = d;
	gender = g;
}
// section -117--74--108--65-1437df22:15bef0504a0:-8000:000000000000087E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Person::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -117--74--108--65-1437df22:15bef0504a0:-8000:0000000000000883 begin
{
	cout << name << ", " << dob << ", " << gender << endl;
}
// section -117--74--108--65-1437df22:15bef0504a0:-8000:0000000000000883 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

string Person::get_name()
{
	return name;
}

string Person::get_dob()
{
	return dob;
}

string Person::get_gender()
{
	return gender;
}

