//Justin Pulido
//Student.cpp
//March 10, 2017
//the student.cpp inherits from person and gets the major
//of the student while using the person.h constructor. 

#include "Student.h"
#include <string>
#include <iostream>

using namespace std;

Student::Student(): Person()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -117--74--108--65-1437df22:15bef0504a0:-8000:0000000000000885 begin
{
	major = "";
}
// section -117--74--108--65-1437df22:15bef0504a0:-8000:0000000000000885 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Student::Student(string n, string d, string g, string m): Person(n, d, g)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -117--74--108--65-1437df22:15bef0504a0:-8000:000000000000088A begin
{
	major = m;
}
// section -117--74--108--65-1437df22:15bef0504a0:-8000:000000000000088A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Student::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -117--74--108--65-1437df22:15bef0504a0:-8000:000000000000088F begin
{
	Person::print();
	cout << " Student, Major: " << major << endl;
}
// section -117--74--108--65-1437df22:15bef0504a0:-8000:000000000000088F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

string Student::get_major()
{
	return major;
}

