Main: Main.o Worker.o Salary_Worker.o Hourly_Worker.o
	g++ -o Main Main.o Salary_Worker.o Hourly_Worker.o

Main.o: Main.cpp
	g++ -c Main.cpp

Worker.o: Worker.cpp
	g++ -c Worker.cpp

Salary_Worker.o: Salary_Worker.cpp
	g++ -c Salary_Worker.cpp

Hourly_Worker.o: Hourly_Worker.cpp
	g++ -c Hourly_Worker.cpp
